pragma solidity ^0.4.18;

contract Sixth {

    uint[3] ex = [1,2,3];
    
    enum Status { New, Pending, Complete, Failed }
    
    Status[] public statuses = [Status.New];

    // function statuses ( uint idx ) public returns (Status) - autogenerated
    function getStatuses () public view returns (Status[]) {
        return statuses;
    }
    
    function addStatus ( Status s ) public {
        statuses.length++;
        statuses[statuses.length-1] = s;
        // Same as statuses.push(s);
    }
    
    function f (uint len) public pure {
        // uint[3] z = [1,2,3];
        uint[3] memory z = [uint256(1),2,3];
        uint8[3] memory zz = [1,2,3];
        
        uint[] memory a = new uint[](7);
    }
    
}